const SCHEDULE = [
    {
        "Day": "Friday",
        "Location": "Supplyframe HQ- 3rd Floor",
        "Time": "9:00 AM",
        "First and Last Name: ": "Doors Open",
        "Presenter Bio (edited, 20-40 words)": "",
        "Talk Title": "",
        "Talk Description (20-40 words)": "",
        "Headshot": "",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "other"
    },
    {
        "Day": "Friday",
        "Location": "Supplyframe HQ- 3rd Floor",
        "Time": "9:00 AM- 5:00 PM",
        "First and Last Name: ": "Registration",
        "Presenter Bio (edited, 20-40 words)": "",
        "Talk Title": "",
        "Talk Description (20-40 words)": "",
        "Headshot": "",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "other"
    },
    {
        "Day": "Friday",
        "Location": "Supplyframe HQ- 3rd Floor",
        "Time": "10:00 AM- 5:00 PM",
        "First and Last Name: ": "Badge Hacking",
        "Presenter Bio (edited, 20-40 words)": "",
        "Talk Title": "",
        "Talk Description (20-40 words)": "",
        "Headshot": "",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "other"
    },
    {
        "Day": "Friday",
        "Location": "Supplyframe HQ- 3rd Floor",
        "Time": "5:00 PM- 10:00 PM",
        "First and Last Name: ": "Supercon Welcome Party ",
        "Presenter Bio (edited, 20-40 words)": "",
        "Talk Title": "",
        "Talk Description (20-40 words)": "",
        "Headshot": "",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": ""
    },
    {
        "Day": "Saturday",
        "Location": "LACM/ DesignLab",
        "Time": "8:30 AM",
        "First and Last Name: ": "Doors Open",
        "Presenter Bio (edited, 20-40 words)": "",
        "Talk Title": "",
        "Talk Description (20-40 words)": "",
        "Headshot": "",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "other"
    },
    {
        "Day": "Saturday",
        "Location": "LACM ",
        "Time": "9:30 AM",
        "First and Last Name: ": "Elliot Williams",
        "Presenter Bio (edited, 20-40 words)": "",
        "Talk Title": "Opening Remarks",
        "Talk Description (20-40 words)": "",
        "Headshot": "",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "other"
    },
    {
        "Day": "Saturday",
        "Location": "LACM",
        "Time": "10:00-10:40 AM",
        "First and Last Name: ": "Charles Lohr",
        "Presenter Bio (edited, 20-40 words)": "CNLohr seeks to break down the barriers of conventional wisdom and common design practices. Whether it’s mapping out wifi in 3D, running Minecraft on a glass microscope slide, or modulating RF signals without dedicated hardware, he seeks to explore what’s possible when layers of abstraction are shed.",
        "Talk Title": "Microcontrollers Are Just Radios in Disguise",
        "Talk Description (20-40 words)": "This talk explores ways to leverage every cycle of underpowered microcontrollers to get them doing the work of parts ten times their price, including operations normally done with dedicated radio hardware. ",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/CNLohr.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "DesignLab ",
        "Time": "10:00-10:20 AM",
        "First and Last Name: ": "Randy Glenn",
        "Presenter Bio (edited, 20-40 words)": "Randy Glenn, an Embedded Systems Engineer, works on firmware for consumer electronics in home automation. He can also be found working on CAN-based pinball systems, lighting systems for halloween, old computers from the 1990s, and other odd microcontroller projects.",
        "Talk Title": "Yes, you CAN use the Controller Area Network outside of cars",
        "Talk Description (20-40 words)": "This talk discusses Controller Area Networks (CAN) used in cars, trains, buses, planes, and spacecraft, but are also useful for all sorts of cases where systems need to communicate. Discover how you can use this technology to transfer data between microcontrollers and larger computers.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Randy-Glenn.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "Supplyframe HQ- 3rd Floor",
        "Time": "10:00-12:00 PM",
        "First and Last Name: ": "Shawn Hymel",
        "Presenter Bio (edited, 20-40 words)": "Shawn Hymel is a consulting engineer and instructor for edge AI and embedded systems that inspire and teach developers of all skill levels. He can be found giving talks, running workshops, and swing dancing in his free time.",
        "Talk Title": "Introduction to Zephyr: Demystifying Device Drivers",
        "Talk Description (20-40 words)": "This workshop is designed for embedded engineers who are new to the Zephyr OS and are interested in exploring how it can be used for building next-generation embedded applications. Participants will gain hands-on experience with Zephyr OS, including initial setup, toggling pins with existing libraries, and creating custom device drivers.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Shawn_Hymel.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "workshop"
    },
    {
        "Day": "Saturday",
        "Location": "DesignLab ",
        "Time": "10:30-10:50 AM",
        "First and Last Name: ": "Nanik Adnani",
        "Presenter Bio (edited, 20-40 words)": "Nanik Adnani, a maker and analog designer, started building things as a kid who liked to sew and knit. Today, Nanik studies and designs analog integrated circuits and works on a variety of projects, everything from discrete transistors to finFETs.",
        "Talk Title": "A Hacker’s Guide to Analog Design in a Digital World",
        "Talk Description (20-40 words)": "This talk provides an overview of the analog circuits found in everyday devices and in many maker projects. Learn why analog design isn’t as hard as you think, and how a few simple concepts could drastically improve your next project.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Nanik_Adnani.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "LACM",
        "Time": "11:00-11:20 AM",
        "First and Last Name: ": "Mohit Bhoite",
        "Presenter Bio (edited, 20-40 words)": "Mohit Bhoite, a senior hardware engineer at Particle, holds a master’s degree in robotics. He designs and builds IoT products and is an avid maker who dedicates his time to building free-formed electronic circuit sculptures. ",
        "Talk Title": "Building space themed circuit sculptures",
        "Talk Description (20-40 words)": "In this talk, hardware engineer and circuit sculptor Mohit Bhoite explores the art of building space-themed free-formed electronic circuit sculptures. Join this talk to learn how anyone with the right tools can get involved in this art form.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Mohit_Bhoite.png",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "DesignLab ",
        "Time": "11:00-11:20 AM",
        "First and Last Name: ": "Dev Kennedy",
        "Presenter Bio (edited, 20-40 words)": "Dev Kennedy began his journey into smart glasses nearly ten years ago when the vision of the concept outpaced available technology. He’s spent the last decade developing the necessary building blocks to make it a reality and is excited to show the world how far it has come. ",
        "Talk Title": "Photonics/Optical Stack for Smart-Glasses ",
        "Talk Description (20-40 words)": "This talk discusses the intricacies of smart glasses and the gamut of hardware options for displaying light, getting the photonics right, and building a head-mounted display. ",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Dev_Kennedy.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "LACM",
        "Time": "11:30-11:50 AM",
        "First and Last Name: ": "Azita Emami",
        "Presenter Bio (edited, 20-40 words)": "Azita Emami is the Andrew and Peggy Cherng Professor of Electrical Engineering and Medical Engineering, and the Director of Center for Sensing to Intelligence (S2I) at Caltech. Her current research interests include integrated circuits and systems, integrated photonics, wearable and implantable devices for neural recording, neural stimulation, sensing, drug delivery and high-speed data communication systems. ",
        "Talk Title": "Intelligent Devices for Brain-Machine-Interfaces and Health Monitoring",
        "Talk Description (20-40 words)": "This talk discusses the design challenges and promises of future wearable and implantable devices. Join us as we take a look at wireless health monitoring with tiny chips, and the hardware-software co-design for Brain-Machine-Interfaces (BMI).",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Azita_Emami.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "DesignLab ",
        "Time": "11:30 -11:50 AM",
        "First and Last Name: ": "James Rowley & Mark Omo",
        "Presenter Bio (edited, 20-40 words)": "Mark Omo, Director of Cat Herding at Marcus Engineering, works primarily in embedded security, electronics, and software. James Rowley, Senior Engineer at Marcus Engineering, works primarily in embedded security and software development. James and Mark both have a background in regulated device design.",
        "Talk Title": "Using an Oscilloscope to Peek Below the Noise Floor: the DSP Magic of Lock-In Amplifiers",
        "Talk Description (20-40 words)": "This talk explores the DSP magic that allows lock-in amplifiers to detect signals hidden below the noise floor. Learn how to use your oscilloscope as a lock-in amplifier, enabling a low-cost entry point to these niche instruments. ",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/James_Rowley.png",
        "Headshot 1/2": "https://hackaday.com/wp-content/uploads/2024/10/Mark_Omo.jpg",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "Alley",
        "Time": "12:00- 1:00 PM",
        "First and Last Name: ": " Lunch",
        "Presenter Bio (edited, 20-40 words)": "",
        "Talk Title": "",
        "Talk Description (20-40 words)": "",
        "Headshot": "",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "other"
    },
    {
        "Day": "Saturday",
        "Location": "Supplyframe HQ- 2nd Floor",
        "Time": "12:30-2:30 PM",
        "First and Last Name: ": "Jazmin Hernandez",
        "Presenter Bio (edited, 20-40 words)": "Jazmin Hernandez is an electronic engineer and language learner currently developing projects that bring students and enthusiasts closer to technology, electronics, and the overall maker community.",
        "Talk Title": "It Matter(s)! Learn to use the Arduino Matter",
        "Talk Description (20-40 words)": "This workshop will teach attendees how to use the Arduino Nano Matter in conjunction with the IoT cloud. It will also cover the basics of Matter protocol and how to connect devices. Beginners are welcome, there’s no prior experience required!",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Jazmin_Hernandez.jpeg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "workshop"
    },
    {
        "Day": "Saturday",
        "Location": "LACM",
        "Time": "1:00-1:20 PM",
        "First and Last Name: ": "Angelica Tavella",
        "Presenter Bio (edited, 20-40 words)": "Angelica Tavella is a design researcher and interaction designer specializing in urban renewable energy and healthy human interactions with technology. Angelica is also a lecturer at the Applied Sciences University of Potsdam and produces experimental electronic music.",
        "Talk Title": "User-Friendly Interfaces for Tomorrow's Energy Management",
        "Talk Description (20-40 words)": "The global shift towards renewable energy sources requires new infrastructure for a more flexible and distributed network. This talk shows source energy metering systems (EMS) can be used to utilize solar power better and gives ideas about how interfaces can become more user-friendly.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Angelica_Tavella.jpeg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "DesignLab ",
        "Time": "1:00-1:40 PM",
        "First and Last Name: ": "Jim Scarletta",
        "Presenter Bio (edited, 20-40 words)": "Jim Scarletta holds a degree in Electronic Engineering from Cal Poly, San Luis Obispo, and has over 30 years of professional engineering and automation experience. Jim is a contractor for wolfSSL focusing on ESP32 embedded development.",
        "Talk Title": "Repurposing ESP32 Based Commercial Products ",
        "Talk Description (20-40 words)": "This talk discusses flashing custom software onto existing commercial ESP32-based products, development, and debugging using open-source Tigard JTAG hardware with VisualGDB in Visual Studio. It will also cover implementing more secure cryptographic functions with commercial-grade wolfSSL examples.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Jim_Scarletta.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "Supplyframe HQ- 3rd Floor",
        "Time": "1:00-3:00 PM",
        "First and Last Name: ": "Paul Beech",
        "Presenter Bio (edited, 20-40 words)": "Paul is the co-founder of UK Maker company Pimoroni and spends his days between cat-herding and making neat PCBs art and kits.",
        "Talk Title": "Mini Robot Jam. Build Hard. Drive Hard.",
        "Talk Description (20-40 words)": "You’ll be given a neat kit of tiny robot parts, and a garage of materials and sensors to build your sweetest ride. Learn how to make the RP2350 at its heart rock ‘n’ roll in MicroPython. Then pit it against obstacles to see how well your code works in real life.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Paul_Beech.jpeg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "workshop"
    },
    {
        "Day": "Saturday",
        "Location": "LACM",
        "Time": "1:30-2:10 PM",
        "First and Last Name: ": "Christina Cyr",
        "Presenter Bio (edited, 20-40 words)": "Christina Cyr specializes in \"Non-Rectangular Phones for Non-Rectangular People\" and holds degrees in physics, biochemistry, and engineering. Her current passions include satellite technology, GNSS, 5G, eco-friendly communication devices, and batteries made from recycled lithium.",
        "Talk Title": "Solving the Last Mile With 3D-printed Packaging",
        "Talk Description (20-40 words)": "This talk explores the complexities of designing product packaging while the product’s design is still evolving. Experience the story of how one maker designed and 3D-printed her own packaging and the lessons she learned along the way. ",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Christina-Cyr.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "DesignLab ",
        "Time": "2:00-2:20 PM",
        "First and Last Name: ": "Juan Diego Zambrano Torres, Ivan Hernandez, and Abdelrahman Tarek Zakaria Abdelmaaboud Farag",
        "Presenter Bio (edited, 20-40 words)": "Juan Diego Zambrano Torres, Ivan Hernandez, and Abdelrahman Tarek Zakaria Abdelmaaboud Faragare are all automation engineering students at Politecnico Di Milano. They all participated in an assistive technology hackathon sponsored by DesignLab and Digikey this year.",
        "Talk Title": "Immersive Motion Rehabilitation Device",
        "Talk Description (20-40 words)": "This talk introduces a wearable motion monitoring device using low-energy Bluetooth (BLE). It features an interactive game-based interface for children and generates detailed medical reports, providing therapists with valuable insights for effective rehabilitation.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Juan-Diego-Ivan-and-Abdelrahman.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "LACM",
        "Time": "2:30- 2:50 PM",
        "First and Last Name: ": "Eduardo Contreras",
        "Presenter Bio (edited, 20-40 words)": "Eduardo Contreras, an electronics engineer, is passionate about technological development and science. Eduardo is the co-founder and CTO of the Electronic Cats company where he develops embedded systems.",
        "Talk Title": "Cats Turned Plumbers: Embedded Linux Adventures",
        "Talk Description (20-40 words)": "This talk explores the journey of deploying embedded Linux systems and integrating drivers on Linux kernels, from the hardware to the kernel.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Eduardo_Contreras.png",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "DesignLab ",
        "Time": "2:30-2:50 PM",
        "First and Last Name: ": "Blair Subbaraman",
        "Presenter Bio (edited, 20-40 words)": "Blair Subbaraman explores machine automation as a creative medium, and how domain experts, such as artists and scientists, can leverage existing skills in their use of machines. Currently based in Seattle, Blair is a PhD student at the University of Washington and works in the lab at Machine Agency. ",
        "Talk Title": "Sketching with Machines",
        "Talk Description (20-40 words)": "Software for making physical things often overlooks existing skill sets, forcing practitioners to work against built-in assumptions to accomplish their goals. This talk will consider how creative practices can guide the development of digital fabrication systems and communities.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Blair-Subbaraman.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "LACM",
        "Time": "3:00-3:20 PM",
        "First and Last Name: ": "Madison Maxey ",
        "Presenter Bio (edited, 20-40 words)": "Madison Maxey spends most of her time working on soft, flexible electronics as CEO and founder of Loomia. She studied materials science and engineering at Stanford University and is the primary inventor on 8 granted patents. ",
        "Talk Title": "E-Textiles for Engineers: A deep dive into performance and applications",
        "Talk Description (20-40 words)": "Think that electronic textiles are only for clothing? Thank again! This talk explores the technical use cases and pros and cons of using e-textiles over other flexible electronic technologies in robotics, automotive and more. From knit e-textile to good ol' regular PCBS, this talk is all about technology comparison and highlighting where electronic textiles can help solve your biggest electromechanical challenges.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Madison_Maxey-.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "DesignLab ",
        "Time": "3:00-3:20 PM",
        "First and Last Name: ": "Joseph Long",
        "Presenter Bio (edited, 20-40 words)": "Joe Long has been tinkering, designing, and hacking electronic systems for about forty years. He is the founder of HackerBoxes.com, the monthly subscription box service for electronics, cybersecurity, and hacker culture. He enjoys teaching electrical engineering and computer science topics to all.",
        "Talk Title": "In Living Color: A New World of Full-Color PCBs",
        "Talk Description (20-40 words)": "This talk will discuss new ways to make full-color PCBs. Gone are the days when printed circuit boards were either boring, bare beige, or coated with a green solder mask. The time for more creative power has arrived. ",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Joseph-Long.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "Supplyframe HQ- 2nd Floor",
        "Time": "3:00-5:00 PM",
        "First and Last Name: ": "Anool Mahidharia",
        "Presenter Bio (edited, 20-40 words)": "Anool is an Electrical Engineer, working in the field of Test & Measurement at Lumetronics, and a contributing writer at Hackaday. He is the co-founder of both WyoLum Emergents and Makers’ Asylum, one of the first community-driven maker spaces in India.",
        "Talk Title": "Blinky Con Badge requires no soldering!",
        "Talk Description (20-40 words)": "Conference badges have become incredibly complex over the years. This workshop will turn the clock back to a simpler time by showcasing a design that can be assembled quickly with simple components and zero soldering.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Anool_Mahidharia.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "workshop"
    },
    {
        "Day": "Saturday",
        "Location": "LACM",
        "Time": "3:30- 3:50 PM",
        "First and Last Name: ": "Mehrdad Majzoobi",
        "Presenter Bio (edited, 20-40 words)": "Mehrdad Majzoobi, the creator of Ubo Pod, is an open-source enthusiast and has spent the last decade working on consumer hardware and software projects. Mehrdad holds a PhD degree in electrical and computer engineering with research in hardware security topics.",
        "Talk Title": "The Secrets of Agile Manufacturing",
        "Talk Description (20-40 words)": "This talk discusses the methods used to design, build, and manufacture the Ubo open source home pod. In particular, it focuses on techniques that can be helpful in small volume production and incremental builds that lower cost, and increase flexibility.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Mehrdad_Majzoobi.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "DesignLab ",
        "Time": "3:30-3:50 PM",
        "First and Last Name: ": "Katherine Connell",
        "Presenter Bio (edited, 20-40 words)": "Katherine \"Smalls\" Connell is a self taught maker who grew up in Silicon Valley helping her dad put together graphic cards. She believes that the maker community is a place to learn things, break things, and do the impossible.\n\n",
        "Talk Title": "Rethinking Body Art With LEDs",
        "Talk Description (20-40 words)": "This talk chronicles the journey of “Sprite Lights,” which are 1.5mm thick LED body art pieces that act like temporary light-up tattoos. From hundreds of prototypes to smelting metal in a driveway to making flexible circuits on a griddle.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Katherine_Connell.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "LACM",
        "Time": "4:00-4:40 PM",
        "First and Last Name: ": "Allie Katz, Samy Kamkar, and Al Williams",
        "Presenter Bio (edited, 20-40 words)": "[Moderator] Allie Katz is an international nonbinary creative technologist, designer, inventor and occasional YouTuber. They're notorious for diving head first into new hardware, and putting entirely too many LEDs in things.\n\nSamy Kamkar is an independent security researcher engineering tools to highlight security implications of everyday technologies. His work's been cited by the NSA, triggered hearings on Capitol Hill, and has advanced security from the device in your pocket to the ones surveilling you from the sky.\n\nAl Williams is a Hackaday editor and contributor. While most of his engineering is done in the forward mode, there was a time when he professionally took apart microprocessors under a microscope to determine why they had failed. ",
        "Talk Title": "Unlocking Designs with Reverse Engineering\n[Panel]",
        "Talk Description (20-40 words)": "",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Allie-Katz.png",
        "Headshot 1/2": "https://hackaday.com/wp-content/uploads/2024/10/Samy_Kamkar.jpg",
        "Headshot 2/2": "https://hackaday.com/wp-content/uploads/2015/07/al-williams-headshot.png",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "DesignLab ",
        "Time": "4:00-4:40 PM",
        "First and Last Name: ": "Justin McAllister & Nick Foster",
        "Presenter Bio (edited, 20-40 words)": "Justin McAllister is a radio enthusiast, electrical engineer, and startup founder who designed uncrewed aerial systems for AeroVironment and co-founded MicaSense. Nick Foster is an electrical engineer specializing in RF, software-defined radios (SDRs), mixed-signal hardware, and developed the first operational ultra-low-latency shortwave radio network.",
        "Talk Title": "Finding Beamo - from interference to numbers stations, how to track down radio transmissions",
        "Talk Description (20-40 words)": "This talk provides a comprehensive guide to identifying and locating radio transmitters. Learn about practical techniques, common tools, and methodologies from decades of combined experience finding, squashing, and mitigating against radio frequency interference. ",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Justin_McAllister-Nick_Foster.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "LACM",
        "Time": "5:00- 5:20 PM",
        "First and Last Name: ": "Jorvon Moss (Odd-Jayy) & Shawn Hymel",
        "Presenter Bio (edited, 20-40 words)": "Jorvon Moss, AKA “Odd Jayy,” is an accomplished Maker best known for his Robotic Oddities. He has a background in art, a BFA in Illustration, and self-taught electronics skills. Shawn Hymel is a consulting engineer and instructor for edge AI and embedded systems.",
        "Talk Title": "Giving Robotic Friends a Voice: Integrating Local LLMs and Speech Systems Into a Companion Bot",
        "Talk Description (20-40 words)": "This talk will showcase a collaborative project that demonstrates full voice interaction on a Digit companion robot and how a large language model (LLM) made this possible. ",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Shawn_Hymel_and_Jorvon_Moss.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "DesignLab ",
        "Time": "5:00-5:20 PM",
        "First and Last Name: ": "Wayne Pavalko",
        "Presenter Bio (edited, 20-40 words)": "Wayne Pavalko is a passionate electronics and hardware tinkerer. After doing a Hackaday-inspired experiment with ocean hardware, he found himself supporting the maritime research community with custom technology.",
        "Talk Title": "Adventures in Ocean Tech: The Maker Buoy Journey",
        "Talk Description (20-40 words)": "This talk discusses Wayne's adventures in ocean technology, from a single Arduino-based drifting buoy to deploying hundreds of ocean sensors around the world. Discover the hardware and software, lessons-learned, and the network of collaborators necessary to turn a hobby into an ocean technology side-hustle.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Wayne_Pavalko.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "LACM",
        "Time": "5:30-6:10 PM",
        "First and Last Name: ": "Shrouk El-Attar",
        "Presenter Bio (edited, 20-40 words)": "Shrouk El-Attar is a renowned electronics engineering consultant and founder of Shrouk El-Attar Consultancy Ltd. Her extensive experience encompasses groundbreaking developments in medical wearables, including innovative projects like COVID-19 emergency ventilators and advanced bionic arms. Recognized as one of the BBC's 100 Most Influential Women and honoured as one of the top 6 Young Women Engineers in the UK, Shrouk has contributed significantly to organisations like Intel and NASA, notably in the Artemis mission bringing humanity back to the moon.",
        "Talk Title": "Watt's Up with Wearables: Navigating the Circuit of IEC 60601 Compliance",
        "Talk Description (20-40 words)": "This talk explores the regulatory challenges of bringing medical wearable devices to market, focusing on IEC 60601 compliance. Shrouk will talk through the practical guidance for navigating safety and efficacy standards in the development of medical electronic wearables.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Shrouk_El-Attar.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Saturday",
        "Location": "LACM",
        "Time": "6:10-6:30 PM ",
        "First and Last Name: ": "Elliot Williams",
        "Presenter Bio (edited, 20-40 words)": "",
        "Talk Title": "State of Hackaday ",
        "Talk Description (20-40 words)": "",
        "Headshot": "",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "other"
    },
    {
        "Day": "Saturday",
        "Location": "Alley/ DesignLab",
        "Time": "7:00 PM- Midnight",
        "First and Last Name: ": "20 Years of Hackaday Party",
        "Presenter Bio (edited, 20-40 words)": "",
        "Talk Title": "",
        "Talk Description (20-40 words)": "",
        "Headshot": "",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "other"
    },
    {
        "Day": "Sunday",
        "Location": "LACM/DesignLab",
        "Time": "9:00 AM",
        "First and Last Name: ": "Doors Open",
        "Presenter Bio (edited, 20-40 words)": "",
        "Talk Title": "",
        "Talk Description (20-40 words)": "",
        "Headshot": "",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "other"
    },
    {
        "Day": "Sunday",
        "Location": "LACM",
        "Time": "10:00-12:00 PM",
        "First and Last Name: ": "Lightning Talks",
        "Presenter Bio (edited, 20-40 words)": "",
        "Talk Title": "",
        "Talk Description (20-40 words)": "",
        "Headshot": "",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "other"
    },
    {
        "Day": "Sunday",
        "Location": "DesignLab ",
        "Time": "10:00-12:00 PM",
        "First and Last Name: ": "Adam McCombs + Isabel Burgos",
        "Presenter Bio (edited, 20-40 words)": "Adam McCombs and Isabel Burgos develop open source hardware for electron and ion microscopes. They have over 10 years of combined experience moving, hacking, rebuilding, and repairing electron microscopes of every vintage and every make.",
        "Talk Title": "Hands on with an Electron Microscope",
        "Talk Description (20-40 words)": "This workshop will teach you how to become an electron microscope knob turner, starting with basic principles and which fields you are actually manipulating in the column. We will also cover sample preparation and considerations, so bring something you want to examine!",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Adam-_McCombs.jpeg\n\n",
        "Headshot 1/2": "https://hackaday.com/wp-content/uploads/2024/10/Isabel_Burgos.jpeg",
        "Headshot 2/2": "",
        "Type": "workshop"
    },
    {
        "Day": "Sunday",
        "Location": "DesignLab ",
        "Time": "11:00-11:20 AM",
        "First and Last Name: ": "Dave Rowntree",
        "Presenter Bio (edited, 20-40 words)": "Dave Rowntree, an electronics engineer with a background in embedded software, IC test, and IC design, manages an electronic prototyping consultancy. Dave is also a foster dad and contributing writer for Hackaday!",
        "Talk Title": "From Consultant to Prototyper on a Shoestring Budget",
        "Talk Description (20-40 words)": "This talk explores the journey of going from an electronics prototyper to a complete systems prototyper as part of a project that includes putting an airbag into a basketball shoe. Find out how the project came to be and how it’s progressing! ",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Dave_Rowntree.png",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Sunday",
        "Location": "DesignLab ",
        "Time": "11:30-11:50 AM",
        "First and Last Name: ": "Zach Fredin",
        "Presenter Bio (edited, 20-40 words)": "Zach Fredin is the senior shop and electronics education technician at The Possible Zone, a Boston non-profit that hosts STEAM education programs. He studied at MIT's Center for Bits and Atoms, and previously founded a neuroscience education hardware startup.",
        "Talk Title": "The Circuit Graver",
        "Talk Description (20-40 words)": "This talk showcases the progress made on a novel fabrication workflow developed over the last several years which demonstrates the feasibility of fabricating 4/4 PCBs at home. Find out how this method can help mitigate delays during design and testing.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Zach_Fredin.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Sunday",
        "Location": "Alley",
        "Time": "12:00- 1:00 PM",
        "First and Last Name: ": "Lunch",
        "Presenter Bio (edited, 20-40 words)": "",
        "Talk Title": "",
        "Talk Description (20-40 words)": "",
        "Headshot": "",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "other"
    },
    {
        "Day": "Sunday",
        "Location": "LACM",
        "Time": "1:00-1:20 PM",
        "First and Last Name: ": "Ayesha Iftiqhar-Wilson",
        "Presenter Bio (edited, 20-40 words)": "Ayesha Iftiqhar-Wilson is an Electrical Engineer passionate about sustainable technology. She has contributed to diverse climate tech initiatives, such as robotics for sustainable farming and electrification of gas-powered tools and vehicles. She is also a dedicated maker and STEAM outreach creator. ",
        "Talk Title": "Environmentally-Friendly Electronics: Design Principles for Sustainability",
        "Talk Description (20-40 words)": "This talk address the issue of electronic waste by introducing Sustainable Design Engineering (SDE) and Design for Environment (DFE) principles. By exploring SDE and DFE, attendees will gain practical insights into integrating environmental considerations into electronics design, fostering a more sustainable approach. ",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Ayesha-Iftiqhar-Wilson.png",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Sunday",
        "Location": "DesignLab ",
        "Time": "1:00-1:20 PM",
        "First and Last Name: ": "Alex Toussaint",
        "Presenter Bio (edited, 20-40 words)": "Alex Toussaint is passionate about drones and ultrasonic sonar. His current project is a mosquito-killing drone that uses sonar to locate and eliminate mosquitoes, with the goal of making entire cities mosquito-free using a cost-effective solution. ",
        "Talk Title": "How to detect (and kill) mosquitoes with off-the-shelf electronics",
        "Talk Description (20-40 words)": "This talk explores the physics of sonar and small insect detection, focusing on the off-the-shelf electronics that allow us to study them cheaply. Learn more about ultrasonic phased arrays, detection, target recognition, and more! ",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Alex_Toussaint.jpeg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Sunday",
        "Location": "LACM",
        "Time": "1:30-1:50 PM",
        "First and Last Name: ": "Andy Kong",
        "Presenter Bio (edited, 20-40 words)": "Andy Kong is an independent researcher working in wearable and implantable technology. His current fascination is with self-powering devices and human sensory augmentation. ",
        "Talk Title": "Human Plants: Open-Source Implants You Don't Need To Recharge",
        "Talk Description (20-40 words)": "Hobbyist implants like magnets and RFID chips have remained largely the same in the last decade, with power systems being the primary challenge. Learn how energy harvesting like piezoelectric, solar, capacitive, and RF could represent the next step for implantable devices. ",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Andy_Kong.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Sunday",
        "Location": "DesignLab ",
        "Time": "1:30-1:50 PM",
        "First and Last Name: ": "Sarah Vollmer",
        "Presenter Bio (edited, 20-40 words)": "Sarah Vollmer is a PhD researcher at York University who focuses on Digital Media and Human Computer Interaction. Her work revolves around enhancing live performances with on-body haptics and improving AR technology with waveguide optics.",
        "Talk Title": "Turning (a lot) of talk into action - friends, foes, and forging ahead. ",
        "Talk Description (20-40 words)": "This talk discusses the journey one maker took through the world of haptics, starting with their first-ever Supercon in 2019. Find out how one talk led to numerous other projects, papers, and large scale digital media exhibitions.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Pink-Pixie-Sarah_Vollmer.jpeg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Sunday",
        "Location": "LACM",
        "Time": "2:00-2:40 PM",
        "First and Last Name: ": "Wenting Zhang",
        "Presenter Bio (edited, 20-40 words)": "Wenting Zhang is an SoC/ digital RTL designer, embedded system application engineer, and open-source maker. He's especially interested in display technologies, and has been building various different projects loosely around the topic of displays.",
        "Talk Title": "Making E-Ink Go Fast",
        "Talk Description (20-40 words)": "The talk will go through the design of the Caster project, which enables high refresh rate and low latency display on off-the-shelf E-Ink screen panels. Find out how this open-source, low-latency display continues to evolve. ",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Wenting_Zhang.jpeg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Sunday",
        "Location": "DesignLab ",
        "Time": "2:00-2:40 PM",
        "First and Last Name: ": "Yohan Hadji",
        "Presenter Bio (edited, 20-40 words)": "Yohan Hadji is a student at the Swiss Federal Institute of Technology in Lausanne (EPFL), and since 2019, he has been working on stratospheric gliders to make radiosondes reusable under the R2HOME project.",
        "Talk Title": "Ultralight Glider Returns Home from the Stratosphere ",
        "Talk Description (20-40 words)": "This talk discusses the challenges of getting a 250-gram sub to autonomously return home after being released from a stratospheric balloon at 100,000 feet. ",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Yohan_Hadji.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Sunday",
        "Location": "LACM",
        "Time": "3:00-3:20 PM",
        "First and Last Name: ": "Priyanka Makin",
        "Presenter Bio (edited, 20-40 words)": "Priyanka Makin is a recent graduate of NYU’s Interactive Telecommunications Program, a SparkFun alum, an electrical engineer, and a multidisciplinary artist. She’s a habitual tinkerer and crafter whose work includes kinetic sculpture, custom circuit boards, audio devices, and sustainable materials. ",
        "Talk Title": "Tech to Hack Embodiment",
        "Talk Description (20-40 words)": "This talk discusses the “Body of Work” series, which is a collection of tech-powered body part sculptures meant to explore the connection between a person and their body. Learn more about the story behind this unique intersection of technology and art.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Priyanka_Makin.png",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Sunday",
        "Location": "DesignLab ",
        "Time": "3:00-3:40 PM",
        "First and Last Name: ": "Kino De Vita & Cat Morse",
        "Presenter Bio (edited, 20-40 words)": "Kino is an artist, musician, and former language teacher turned electronics nerd through their love of synthesizers and electronic instruments. Cat Morse is a designer and maker compelled by the beauty of objects, functionality, and human interaction.",
        "Talk Title": "Celebrating the World of Display Technology",
        "Talk Description (20-40 words)": "In this two-part presentation, Cat Morse will take the audience through the story of the PCC Time Machine, a retro-tech clock, and Kino DeVita will talk about curating and designing the first-ever community-sourced exhibit dedicated to electronic display technology.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Kino-DeVita.jpeg",
        "Headshot 1/2": "https://hackaday.com/wp-content/uploads/2024/10/Cat-Morse.jpg",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Sunday",
        "Location": "LACM",
        "Time": "3:30-3:50 PM",
        "First and Last Name: ": "Cedric Honnet",
        "Presenter Bio (edited, 20-40 words)": "Cedric Honnet is a PhD student in Human-Computer Interaction, focused on wearables. Before his PhD, he worked for a decade in embedded systems and scalable manufacturing, but spent half of his time in hackerspaces or research labs, experimenting with open-source projects such as eTextile music controllers or miniature 3D positioning for dance performances.",
        "Talk Title": "FiberCircuits: Miniature Flex Circuits Inside Fibers, for Interactive eTextiles",
        "Talk Description (20-40 words)": "This talk explores the miniaturization of electronic circuits to be woven (or knitted) into textiles. Both about DIY and scalable manufacturing, it will address techniques for high density flex circuits, miniature part tricks, encapsulation, and firmware tips. As a conclusion, a note about the Shenzhen manufactuing echosystem will be included.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Cedric-Honnet.png",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Sunday",
        "Location": "LACM",
        "Time": "4:00-4:40 PM",
        "First and Last Name: ": "Janelle Wellons",
        "Presenter Bio (edited, 20-40 words)": "Janelle Wellons is a Senior Mission Operations Engineer at ispace, inc., leading routine and critical space operations from the HAKUTO-R Mission Control Center as a Flight Director for the companies’ lunar lander missions. She previously worked at NASA Jet Propulsion Laboratory, where she was awarded the Bruce Murray Award for inspiring students to engage in STEM.",
        "Talk Title": "Behind the Scenes of Mission Control",
        "Talk Description (20-40 words)": "After 7 years operating science instruments and spacecraft at the Moon, Saturn, and our own planet Earth, Janelle will be uncovering the pillars of spaceflight operations. During this talk, she will take you behind the scenes of mission control from the perspective of a Flight Director to share how we navigate the stars, survive the uncertainty of space, and make a difference for humanity.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Janelle-Wellons.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Sunday",
        "Location": "DesignLab ",
        "Time": "4:00-4:40 PM",
        "First and Last Name: ": "Joshua Wise",
        "Presenter Bio (edited, 20-40 words)": "Joshua Wise, as half of Accelerated Tech, Inc., is an experienced all-purpose computer software and hardware engineer. He is somewhat better at racing Advent of Code than he is at racing cyclocross, despite causing about an equal number of crashes in each.",
        "Talk Title": "X1Plus: an unusual custom firmware for a consumer 3D printer",
        "Talk Description (20-40 words)": "In this talk, we’ll laugh together about some classic IoT exploits, puzzle over patching a compiled monolithic firmware, and even take the opportunity to be a little hopeful about whether vendors will ever get the message about user freedoms.",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Joshua_Wise.png",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "speaker"
    },
    {
        "Day": "Sunday",
        "Location": "LACM",
        "Time": "5:00-6:30 PM",
        "First and Last Name: ": "Badge Hacking + SAO Prize Ceremony",
        "Presenter Bio (edited, 20-40 words)": "",
        "Talk Title": "",
        "Talk Description (20-40 words)": "",
        "Headshot": "",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "other"
    },
    {
        "Day": "Friday",
        "Location": "Supplyframe HQ- 2nd Floor",
        "Time": "1:00-2:30 PM + 3:00-4:30 PM",
        "First and Last Name: ": "Matt Venn",
        "Presenter Bio (edited, 20-40 words)": "Matt Venn is a science and technology communicator and electronics engineer. He has been involved with open-source silicon for the last four years and sent over 20 chips for manufacturing. ",
        "Talk Title": "Tiny Tapeout",
        "Talk Description (20-40 words)": "In this workshop, participants will get the opportunity to design and manufacture your own design on an ASIC! Participants will learn the basics of digital logic, the basics of how semiconductors are designed and made, how to use an online digital design tool to build and simulate a simple design, and how to create the GDS files for manufacture on the open-source Sky130 PDK. Participants will have the option to submit their designs to be manufactured on the next shuttle as part of the Tiny Tapeout project.\n",
        "Headshot": "https://hackaday.com/wp-content/uploads/2024/10/Matt_Venn.jpg",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "workshop"
    },
    {
        "Day": "",
        "Location": "",
        "Time": "Daily",
        "First and Last Name: ": "Krux",
        "Presenter Bio (edited, 20-40 words)": "An experiential scavenger hunt.",
        "Talk Title": "Side Quests ",
        "Talk Description (20-40 words)": "",
        "Headshot": "",
        "Headshot 1/2": "",
        "Headshot 2/2": "",
        "Type": "Other"
    }
]